---
version: '3'

services:
  r-tidyverse:
    container_name: r-tidyverse
    build:
      context: .
    image: dceoy/r-tidyverse:latest
    user: ${UID}:${GID}
    userns_mode: host
    volumes:
      - ${PWD}:/wd
    working_dir: /wd
    entrypoint:
      - /usr/bin/R
    command:
      - --vanilla
