version: '3'

services:
  r-tidyverse:
    container_name: r-tidyverse
    build:
      context: .
    image: dceoy/r-tidyverse:latest
    user: ${UID}:${GID}
    volumes:
      - ${PWD}:/work
    working_dir: /work
